[[redirects]]
  from = "/"
  to = "/docs/get-started/quickstart/"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/docs/get-started/quickstart/"
  status = 301
  force = true

[[redirects]]
  from = "https://developers.livesession.io/*"
  to = "https://livesession.dev/:splat"
  status = 301
  force = true