[[redirects]]
  from = "https://developers.livesession.io/*"
  to = "https://livesession.dev/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "/"
  to = "/docs/get-started/quickstart/"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/docs/get-started/quickstart/"
  status = 301
  force = true

[[redirects]]
  from = "/javascript-api/platforms"
  to = "/docs/get-started/frameworks"
  status = 301
  force = true

[[redirects]]
  from = "/javascript-api/methods"
  to = "/docs/api/browser/methods"
  status = 301
  force = true

[[redirects]]
  from = "/javascript-api/introduction"
  to = "/docs/api/browser/introduction"
  status = 301
  force = true